### ISSUE TITLE
e, ə 是否要交換一下？

### ISSUE THREAD

**Issue by osfans** [Fenzland/fongz-pinin#1]
或者用ɛ

**Comment by osfans** [comment]
另外，爲了方便輸入，我們方言拼音中ɛ是寫成ae。

解jiae

**Comment by Fenzland** [comment]
@osfans 
謝謝您的寶貴意見和討論，抱歉兩年後纔回覆。由於是基於《現代漢語拼音》，因此會儘可能保留其中一些習慣：`e`表示國際音標`[ə]`，以及`b`,`d`,`g`表示清輔音，`-h`表示捲舌而非送氣音等，不追求與國際音標一致。不過這個例子正好是兩個音用反過來了確實不太好。我採納了您的意見改爲 `ɛ`。

至於採用大寫字母還是多個小寫字母表示單音，我個人傾向於使用大寫字母；但同時也理解更多的人可能更傾向於不使用大寫字母。如果我的方案中每一個大寫字母都找到合適的小寫拼法，我很願意增加一套純小寫的方案。
不過我大概不會使用 `ae` 拼出 `ɛ`，因爲這個組合像極了 `æ`，可能會選擇 `ea` 這樣的組合吧。`ü` 的小寫拼法可能會選擇 `iu`，濁音暫時考慮用 `-r`。預計還會引入 `[ɯ]`,`[ɑ]` 等音，因此會晚些再做這件事。
也希望能得到您的寶貴意見。
